import { useCallback, useState } from 'react'
import { supabase } from '../lib/supabase'
import { todayKey } from '../context/AppContext'

function expectedFirstPhrase(identity) {
  return identity === 'Addin' ? 'i love you risma' : 'i love you addin'
  }

  function expectedSecondPhrase(firstUser) {
    return `i love you too ${firstUser.toLowerCase()}`
    }

    function normalize(text) {
      return text.trim().toLowerCase().replace(/\s+/g, ' ')
      }

      export function useDailyLogin() {
        const [loading, setLoading] = useState(false)
          const [error, setError] = useState(null)

            const fetchTodayRow = useCallback(async () => {
                const { data, error } = await supabase
                      .from('daily_logins')
                            .select('*')
                                  .eq('login_date', todayKey())
                                        .maybeSingle()

                                            if (error) throw error
                                                return data
                                                  }, [])

                                                    const getRequirement = useCallback(
                                                        async (identity) => {
                                                              setLoading(true)
                                                                    setError(null)
                                                                          try {
                                                                                  const row = await fetchTodayRow()

                                                                                          if (!row) {
                                                                                                    return {
                                                                                                                requiresPhrase: true,
                                                                                                                            expectedPhrase: expectedFirstPhrase(identity),
                                                                                                                                        alreadyVisitedBy: null,
                                                                                                                                                    alreadyCheckedInSelf: false,
                                                                                                                                                                row: null,
                                                                                                                                                                          }
                                                                                                                                                                                  }

                                                                                                                                                                                          if (!row.second_user) {
                                                                                                                                                                                                    if (row.first_user === identity) {
                                                                                                                                                                                                                return {
                                                                                                                                                                                                                              requiresPhrase: false,
                                                                                                                                                                                                                                            expectedPhrase: null,
                                                                                                                                                                                                                                                          alreadyVisitedBy: null,
                                                                                                                                                                                                                                                                        alreadyCheckedInSelf: true,
                                                                                                                                                                                                                                                                                      row,
                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                      return {
                                                                                                                                                                                                                                                                                                                                  requiresPhrase: true,
                                                                                                                                                                                                                                                                                                                                              expectedPhrase: expectedSecondPhrase(row.first_user),
                                                                                                                                                                                                                                                                                                                                                          alreadyVisitedBy: row.first_user,
                                                                                                                                                                                                                                                                                                                                                                      alreadyCheckedInSelf: false,
                                                                                                                                                                                                                                                                                                                                                                                  row,
                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                            const partner = row.first_user === identity ? row.second_user : row.first_user
                                                                                                                                                                                                                                                                                                                                                                                                                    return {
                                                                                                                                                                                                                                                                                                                                                                                                                              requiresPhrase: false,
                                                                                                                                                                                                                                                                                                                                                                                                                                        expectedPhrase: null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                  alreadyVisitedBy: partner,
                                                                                                                                                                                                                                                                                                                                                                                                                                                            alreadyCheckedInSelf: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      row,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            setError(err.message)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              requiresPhrase: false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        expectedPhrase: null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  alreadyVisitedBy: null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            alreadyCheckedInSelf: false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      row: null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                offline: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              } finally {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      setLoading(false)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    [fetchTodayRow]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const submitLogin = useCallback(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            async (identity, typedPhrase, requirement) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  setLoading(true)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        setError(null)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (!requirement.requiresPhrase) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return { success: true }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (normalize(typedPhrase) !== normalize(requirement.expectedPhrase)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      success: false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  message: 'Belum pas nih, coba ketik ulang persis seperti contoh ya ❤️',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const now = new Date().toISOString()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (!requirement.row) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const { error } = await supabase.from('daily_logins').insert({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          login_date: todayKey(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      first_user: identity,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  first_login_at: now,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (error) throw error
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return { success: true }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const { error } = await supabase
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          .from('daily_logins')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .update({ second_user: identity, second_login_at: now })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              .eq('id', requirement.row.id)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (error) throw error
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return { success: true }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            setError(err.message)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return { success: true, offline: true }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          } finally {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  setLoading(false)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                []
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return { getRequirement, submitLogin, loading, error }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }