import { useCallback, useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'
import { playSfx } from '../lib/sfx'

const PHOTOS_BUCKET = 'photos'

function publicUrlFor(path) {
  if (!path) return null
    const { data } = supabase.storage.from(PHOTOS_BUCKET).getPublicUrl(path)
      return data?.publicUrl ?? null
      }

      export function usePhotos() {
        const [photos, setPhotos] = useState([])
          const [albums, setAlbums] = useState([])
            const [loading, setLoading] = useState(true)
              const [error, setError] = useState(null)

                const fetchAlbums = useCallback(async () => {
                    const { data, error } = await supabase
                          .from('albums')
                                .select('*')
                                      .order('created_at', { ascending: true })
                                          if (error) {
                                                setError(error.message)
                                                      return []
                                                          }
                                                              setAlbums(data || [])
                                                                  return data || []
                                                                    }, [])

                                                                      const fetchPhotos = useCallback(async () => {
                                                                          setLoading(true)
                                                                              const { data, error } = await supabase
                                                                                    .from('photos')
                                                                                          .select('*')
                                                                                                .order('created_at', { ascending: false })

                                                                                                    if (error) {
                                                                                                          setError(error.message)
                                                                                                                setLoading(false)
                                                                                                                      return
                                                                                                                          }

                                                                                                                              const withUrls = (data || []).map((p) => ({
                                                                                                                                    ...p,
                                                                                                                                          url: publicUrlFor(p.storage_path),
                                                                                                                                              }))

                                                                                                                                                  setPhotos(withUrls)
                                                                                                                                                      setLoading(false)
                                                                                                                                                        }, [])

                                                                                                                                                          useEffect(() => {
                                                                                                                                                              fetchAlbums()
                                                                                                                                                                  fetchPhotos()
                                                                                                                                                                    }, [fetchAlbums, fetchPhotos])

                                                                                                                                                                      const uploadPhoto = useCallback(
                                                                                                                                                                          async ({ file, title, story, albumId, uploadedBy }) => {
                                                                                                                                                                                setError(null)
                                                                                                                                                                                      const ext = file.name.split('.').pop()
                                                                                                                                                                                            const path = `${uploadedBy?.toLowerCase() || 'shared'}/${Date.now()}-${Math.random()
                                                                                                                                                                                                    .toString(36)
                                                                                                                                                                                                            .slice(2, 8)}.${ext}`

                                                                                                                                                                                                                  const { error: uploadError } = await supabase.storage
                                                                                                                                                                                                                          .from(PHOTOS_BUCKET)
                                                                                                                                                                                                                                  .upload(path, file, { cacheControl: '3600', upsert: false })

                                                                                                                                                                                                                                        if (uploadError) {
                                                                                                                                                                                                                                                setError(uploadError.message)
                                                                                                                                                                                                                                                        return { success: false, message: uploadError.message }
                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                    const { error: insertError } = await supabase.from('photos').insert({
                                                                                                                                                                                                                                                                            title: title || null,
                                                                                                                                                                                                                                                                                    story: story || null,
                                                                                                                                                                                                                                                                                            album_id: albumId || null,
                                                                                                                                                                                                                                                                                                    storage_path: path,
                                                                                                                                                                                                                                                                                                            uploaded_by: uploadedBy || null,
                                                                                                                                                                                                                                                                                                                    is_favorite: false,
                                                                                                                                                                                                                                                                                                                          })

                                                                                                                                                                                                                                                                                                                                if (insertError) {
                                                                                                                                                                                                                                                                                                                                        setError(insertError.message)
                                                                                                                                                                                                                                                                                                                                                return { success: false, message: insertError.message }
                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                            await fetchPhotos()
                                                                                                                                                                                                                                                                                                                                                                  playSfx('cameraShutter')
                                                                                                                                                                                                                                                                                                                                                                        return { success: true }
                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                [fetchPhotos]
                                                                                                                                                                                                                                                                                                                                                                                  )

                                                                                                                                                                                                                                                                                                                                                                                    const deletePhoto = useCallback(async (photo) => {
                                                                                                                                                                                                                                                                                                                                                                                        setError(null)
                                                                                                                                                                                                                                                                                                                                                                                            if (photo.storage_path) {
                                                                                                                                                                                                                                                                                                                                                                                                  await supabase.storage.from(PHOTOS_BUCKET).remove([photo.storage_path])
                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                          const { error } = await supabase.from('photos').delete().eq('id', photo.id)
                                                                                                                                                                                                                                                                                                                                                                                                              if (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                    setError(error.message)
                                                                                                                                                                                                                                                                                                                                                                                                                          return { success: false }
                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                  setPhotos((prev) => prev.filter((p) => p.id !== photo.id))
                                                                                                                                                                                                                                                                                                                                                                                                                                      return { success: true }
                                                                                                                                                                                                                                                                                                                                                                                                                                        }, [])

                                                                                                                                                                                                                                                                                                                                                                                                                                          const updatePhoto = useCallback(async (id, updates) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                              setError(null)
                                                                                                                                                                                                                                                                                                                                                                                                                                                  const { error } = await supabase.from('photos').update(updates).eq('id', id)
                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                            setError(error.message)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return { success: false }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          setPhotos((prev) => prev.map((p) => (p.id === id ? { ...p, ...updates } : p)))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return { success: true }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }, [])

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const toggleFavorite = useCallback(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      async (photo) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            playSfx('heartPop')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return updatePhoto(photo.id, { is_favorite: !photo.is_favorite })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          [updatePhoto]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const createAlbum = useCallback(async (name, createdBy) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  setError(null)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const { data, error } = await supabase
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .from('albums')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  .insert({ name, created_by: createdBy || null })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .select()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              .single()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        setError(error.message)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return { success: false }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      setAlbums((prev) => [...prev, data])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return { success: true, album: data }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }, [])

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  photos, albums, loading, error,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      fetchPhotos, fetchAlbums, uploadPhoto, deletePhoto, updatePhoto, toggleFavorite, createAlbum,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }