import { AnimatePresence, motion } from 'framer-motion'
import { Heart, X, Pencil, Trash2, ChevronLeft, ChevronRight } from 'lucide-react'

const SWIPE_THRESHOLD = 80

export default function PhotoViewer({ photos, index, onClose, onChangeIndex, onToggleFavorite, onEdit, onDelete }) {
  const photo = photos[index]
    if (!photo) return null

      const hasPrev = index > 0
        const hasNext = index < photos.length - 1

          function handleDragEnd(_, info) {
              const { offset, velocity } = info
                  if (offset.y > 120 && Math.abs(offset.x) < 80) {
                        onClose()
                              return
                                  }
                                      if (offset.x < -SWIPE_THRESHOLD && hasNext) {
                                            onChangeIndex(index + 1)
                                                } else if (offset.x > SWIPE_THRESHOLD && hasPrev) {
                                                      onChangeIndex(index - 1)
                                                          } else if (Math.abs(velocity.x) > 500) {
                                                                if (velocity.x < 0 && hasNext) onChangeIndex(index + 1)
                                                                      if (velocity.x > 0 && hasPrev) onChangeIndex(index - 1)
                                                                          }
                                                                            }

                                                                              return (
                                                                                  <AnimatePresence>
                                                                                        <motion.div
                                                                                                initial={{ opacity: 0 }}
                                                                                                        animate={{ opacity: 1 }}
                                                                                                                exit={{ opacity: 0 }}
                                                                                                                        className="fixed inset-0 z-50 flex flex-col bg-plum-700/90 backdrop-blur-md"
                                                                                                                              >
                                                                                                                                      <div className="flex items-center justify-between p-4">
                                                                                                                                                <button onClick={onClose} className="flex h-10 w-10 items-center justify-center rounded-full bg-white/15 text-white active:scale-90" aria-label="Tutup">
                                                                                                                                                            <X size={20} />
                                                                                                                                                                      </button>
                                                                                                                                                                                <div className="flex gap-2">
                                                                                                                                                                                            <button onClick={() => onEdit(photo)} className="flex h-10 w-10 items-center justify-center rounded-full bg-white/15 text-white active:scale-90" aria-label="Edit">
                                                                                                                                                                                                          <Pencil size={18} />
                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                  <button onClick={() => onDelete(photo)} className="flex h-10 w-10 items-center justify-center rounded-full bg-white/15 text-white active:scale-90" aria-label="Hapus">
                                                                                                                                                                                                                                                <Trash2 size={18} />
                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                      <div className="relative flex flex-1 items-center justify-center overflow-hidden px-2">
                                                                                                                                                                                                                                                                                                {hasPrev && (
                                                                                                                                                                                                                                                                                                            <button onClick={() => onChangeIndex(index - 1)} className="absolute left-2 z-10 hidden h-10 w-10 items-center justify-center rounded-full bg-white/15 text-white sm:flex" aria-label="Sebelumnya">
                                                                                                                                                                                                                                                                                                                          <ChevronLeft size={22} />
                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                )}

                                                                                                                                                                                                                                                                                                                                                          <motion.div
                                                                                                                                                                                                                                                                                                                                                                      key={photo.id}
                                                                                                                                                                                                                                                                                                                                                                                  className="flex h-full w-full items-center justify-center"
                                                                                                                                                                                                                                                                                                                                                                                              drag
                                                                                                                                                                                                                                                                                                                                                                                                          dragElastic={0.2}
                                                                                                                                                                                                                                                                                                                                                                                                                      onDragEnd={handleDragEnd}
                                                                                                                                                                                                                                                                                                                                                                                                                                  initial={{ opacity: 0, scale: 0.96 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                              animate={{ opacity: 1, scale: 1 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                          exit={{ opacity: 0, scale: 0.96 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      transition={{ duration: 0.25 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <img src={photo.url} alt={photo.title || 'Memory'} className="max-h-full max-w-full select-none rounded-2xl object-contain shadow-glass-lg" draggable={false} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </motion.div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {hasNext && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button onClick={() => onChangeIndex(index + 1)} className="absolute right-2 z-10 hidden h-10 w-10 items-center justify-center rounded-full bg-white/15 text-white sm:flex" aria-label="Selanjutnya">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <ChevronRight size={22} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="glass-panel mx-4 mb-4 max-h-48 overflow-y-auto px-5 py-4 text-plum-600">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="flex items-start justify-between gap-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {photo.title && <h3 className="text-lg font-semibold">{photo.title}</h3>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {photo.story && <p className="mt-1 text-sm leading-relaxed text-plum-500">{photo.story}</p>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {!photo.title && !photo.story && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="text-sm italic text-plum-400">Belum ada cerita untuk foto ini ❤️</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {photo.uploaded_by && <p className="mt-2 text-xs text-plum-400">Diunggah oleh {photo.uploaded_by}</p>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button onClick={() => onToggleFavorite(photo)} className="flex h-10 w-10 flex-shrink-0 items-center justify-center rounded-full bg-blush-50 active:scale-90" aria-label="Favorite">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Heart size={20} className={photo.is_favorite ? 'fill-blush-600 text-blush-600' : 'text-plum-400'} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </AnimatePresence>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }