import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { X, ImagePlus, Loader2 } from 'lucide-react'

export default function PhotoUploadModal({ open, onClose, albums, onUpload, onCreateAlbum, uploadedBy }) {
  const [file, setFile] = useState(null)
    const [preview, setPreview] = useState(null)
      const [title, setTitle] = useState('')
        const [story, setStory] = useState('')
          const [albumId, setAlbumId] = useState('')
            const [newAlbum, setNewAlbum] = useState('')
              const [submitting, setSubmitting] = useState(false)
                const [error, setError] = useState(null)

                  function reset() {
                      setFile(null); setPreview(null); setTitle(''); setStory(''); setAlbumId(''); setNewAlbum(''); setError(null)
                        }

                          function handleFileChange(e) {
                              const f = e.target.files?.[0]
                                  if (!f) return
                                      setFile(f)
                                          setPreview(URL.createObjectURL(f))
                                            }

                                              async function handleSubmit(e) {
                                                  e.preventDefault()
                                                      if (!file) { setError('Pilih foto dulu ya ❤️'); return }
                                                          setSubmitting(true)
                                                              setError(null)

                                                                  let finalAlbumId = albumId || null
                                                                      if (albumId === '__new__' && newAlbum.trim()) {
                                                                            const res = await onCreateAlbum(newAlbum.trim(), uploadedBy)
                                                                                  finalAlbumId = res.success ? res.album.id : null
                                                                                      } else if (albumId === '__new__') {
                                                                                            finalAlbumId = null
                                                                                                }

                                                                                                    const result = await onUpload({ file, title: title.trim(), story: story.trim(), albumId: finalAlbumId, uploadedBy })
                                                                                                        setSubmitting(false)

                                                                                                            if (result.success) { reset(); onClose() } else { setError(result.message || 'Gagal mengunggah, coba lagi ya.') }
                                                                                                              }

                                                                                                                return (
                                                                                                                    <AnimatePresence>
                                                                                                                          {open && (
                                                                                                                                  <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-50 flex items-end justify-center bg-plum-700/50 backdrop-blur-sm sm:items-center" onClick={onClose}>
                                                                                                                                            <motion.form onClick={(e) => e.stopPropagation()} onSubmit={handleSubmit} initial={{ y: '100%' }} animate={{ y: 0 }} exit={{ y: '100%' }} transition={{ type: 'spring', damping: 28, stiffness: 280 }} className="glass-panel max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-b-none p-6 sm:rounded-3xl">
                                                                                                                                                        <div className="mb-4 flex items-center justify-between">
                                                                                                                                                                      <h2 className="text-lg font-semibold text-plum-600">Tambah Foto</h2>
                                                                                                                                                                                    <button type="button" onClick={onClose} className="flex h-9 w-9 items-center justify-center rounded-full bg-white/60 active:scale-90">
                                                                                                                                                                                                    <X size={18} />
                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                          <label className="mb-4 flex h-40 cursor-pointer items-center justify-center rounded-2xl border-2 border-dashed border-blush-300 bg-white/40 text-center">
                                                                                                                                                                                                                                                        {preview ? (
                                                                                                                                                                                                                                                                        <img src={preview} alt="Preview" className="h-full w-full rounded-2xl object-cover" />
                                                                                                                                                                                                                                                                                      ) : (
                                                                                                                                                                                                                                                                                                      <span className="flex flex-col items-center gap-2 text-blush-600">
                                                                                                                                                                                                                                                                                                                        <ImagePlus size={28} />
                                                                                                                                                                                                                                                                                                                                          <span className="text-sm font-medium">Pilih foto dari galeri</span>
                                                                                                                                                                                                                                                                                                                                                          </span>
                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                      <input type="file" accept="image/*" onChange={handleFileChange} className="hidden" />
                                                                                                                                                                                                                                                                                                                                                                                                  </label>

                                                                                                                                                                                                                                                                                                                                                                                                              <div className="space-y-3">
                                                                                                                                                                                                                                                                                                                                                                                                                            <input type="text" placeholder="Judul foto (opsional)" value={title} onChange={(e) => setTitle(e.target.value)} className="input-field" />
                                                                                                                                                                                                                                                                                                                                                                                                                                          <textarea placeholder="Ceritanya gimana nih? (opsional)" value={story} onChange={(e) => setStory(e.target.value)} rows={3} className="input-field resize-none" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <select value={albumId} onChange={(e) => setAlbumId(e.target.value)} className="input-field">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <option value="">Tanpa album</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {albums.map((a) => (<option key={a.id} value={a.id}>{a.name}</option>))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <option value="__new__">+ Buat album baru</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {albumId === '__new__' && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <input type="text" placeholder="Nama album baru" value={newAlbum} onChange={(e) => setNewAlbum(e.target.value)} className="input-field" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {error && <p className="mt-3 text-sm text-blush-700">{error}</p>}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button type="submit" disabled={submitting} className="btn-primary mt-5 w-full">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {submitting ? <Loader2 size={18} className="animate-spin" /> : 'Simpan ke Vault'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </motion.form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </AnimatePresence>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }